name: development

on:
  push:
  pull_request:

jobs:
  build:
    name: Build & Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "npm"

      - name: Restore Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run Unit Tests
        run: npm run test:unit

      - name: Build Projects
        run: npm run build

  integration:
    name: Integration Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [edge, chrome, firefox]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "npm"

      - name: Restore Dependencies
        run: npm ci

      - name: Lint E2E
        run: npm run lint:e2e

      - name: Build
        run: npm run build

      - name: Run Integration Tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run preview
          browser: ${{ matrix.browser }}
