name: development

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "npm"

      - name: Restore Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run Unit Tests
        run: npm run test -- --coverage

      - name: Build Projects
        run: npm run build
